### ISSUE TITLE
Nic nie dziaa.

### ISSUE THREAD

**Issue by Diptrickov** [WIITD/mechadron#1]
Jak w tytule.
PS Opla sprzedam.

**Comment by Diptrickov** [comment]
Tyle co dyrko dał
PS Jak działa jak nie działa?

**Comment by WIITD** [comment]
A to nie.
PS: Panie, działa i basta!

**Comment by Diptrickov** [comment]
Dupa tam panie. Nic w tym dronie nie działa. Widzę, że tu pomocy nie znajdę, niniejszym zamykam. Nie pozdrawiam.
