### ISSUE TITLE
Nie rozumim

### ISSUE THREAD

**Issue by Diptrickov** [WIITD/mechadron#2]
Nie rozumim opisu projektu readme bo jest po angielsku. Halp.

**Comment by WIITD** [comment]
I'm really sorry mister, but I believe I can't understand you

**Comment by Diptrickov** [comment]
Byś się polskiego angolu nauczył, rozwinąłbyś się i byś mógł po ludzku napisać a nie w języku kraju gdzie do burgera karabin dodają. Wielka Lechia jeszcze powróci i będziesz żałował żeś się chamie polskiego nie uczył.

**Comment by WIITD** [comment]
I'm really sorry mister, but I believe I can't understand you, I believe I need to close this issue

**Comment by Diptrickov** [comment]
Nie ma tak łatwo chamie nie pomogłeś nie zamykasz. Ucz się polskiego ciulu i zrób tak żeby było dobrze!

**Comment by WIITD** [comment]
Ja witać, do przetłumaczyć ten tekst używszy słownik język polski, trudno mi jest zrozumić twoje gawożenie, chciałbym zachęcić ciebia do użycia język angolski

**Comment by Diptrickov** [comment]
coraz lepiej ale cały czas jak debil piszesz. Naucz się po polskiemu i opis na polski zmień chamie.

**Comment by WIITD** [comment]
Dobra, panie. Co mi pan pracowników męczy, Narzekają mi że jakiś oszołom po rosyjsku pisze na tym hubie. Naucz się pan po anglijsku gdać bo polski support da dużo kosztuje i się opierdala cały czas a te hindusy to pracują jak za 3.

**Comment by Diptrickov** [comment]
Nie udawaj kurwa ze z twojego konta jakiś ukrainiec pisze jak wiem że to ty cały czas. Naucz się po polsku bo jak z moimi husarami cię dojadę to pożałujesz. Elo.

**Comment by WIITD** [comment]
और भाड़ में जाओ
